PATCH http://localhost:3001/tasks
Content-Type : application/json

{
  "_id":"69523766056688e7032b3030",
  "title":"updated-task",
  "dueDate":"2025-01-01T12:00:00Z",
  "description":"dsfkjsdfksflknskfjdnskfnklsnflksnflknskfnklsdfnknflasnfkjsnfdkjn",
  "priority":"normal",
  "status":"todo"
}