POST http://localhost:3001/tasks
Content-Type: application/json

{
  "title":"excercise 78",
  "dueDate":"2025-01-01T12:00:00Z",
  "description":"dsfkjsdfksflknskfjdnskfnklsnflksnflk",
  "priority":"normal",
  "status":"todo",
  "extra":"extra content"
}