POST http://localhost:3001/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTVhNDZjYjUxN2IyNTEwMGQyNjM1MWUiLCJlbWFpbCI6ImpvaG5AZG9lLmNvbSIsImlhdCI6MTc2ODkwMjQ4MywiZXhwIjoxNzY4OTg4ODgzfQ.ZE855i2AQ1dTSTjVNEYQD4GKzi1rbQ2PHJEuPo-Fgsg

{
  "title":"excercise 897",
  "dueDate":"2025-01-01T12:00:00Z",
  "description":"dsfkjsdfksflknskfjdnskfnklsnflksnflk",
  "priority":"normal",
  "status":"todo",
  "extra":"extra content"
}